swiftmailer:
    transport: gmail
    username: "%env(MAILER_USER)%"
    password:
    host: smtp.gmail.com
    port: 465
    encryption: ssl
    auth-mode: login
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
