swiftmailer:
    transport: gmail
    username: "%env(MAILER_USER)%"
    password: groupw2k9
    host: smtp.gmail.com
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
