#index:
#    path: /
#    controller: App\Controller\DefaultController::index


homepage:
    path: /
    controller: App\Controller\HomePageController::Wellcoming

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    path: /admin
    controller: App\Controller\AdminController::admin
