#index:
#    path: /
#    controller: App\Controller\DefaultController::index


homepage:
    path: /
    controller: App\Controller\HomePageController::Welcoming


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"